### ISSUE TITLE
[Improvement]: Update Netty dependency version in Redis connector

### ISSUE THREAD

**Issue by Shairam** [ballerina-platform/ballerina-extended-library#433]
### Connector Name

module/redis (Redis)

### Suggested improvement

It seems that we observe the following jar conflicts warnings when using `redis` and `http` connector together. 

```
'netty-transport-4.1.71.Final.jar' dependency of 'ballerinax/redis' conflict with 'netty-transport-4.1.77.Final.jar' dependency of 'ballerina/http'
                'netty-codec-4.1.71.Final.jar' dependency of 'ballerinax/redis' conflict with 'netty-codec-4.1.77.Final.jar' dependency of 'ballerina/http'
                'netty-resolver-4.1.71.Final.jar' dependency of 'ballerinax/redis' conflict with 'netty-resolver-4.1.77.Final.jar' dependency of 'ballerina/http'
                'netty-buffer-4.1.71.Final.jar' dependency of 'ballerinax/redis' conflict with 'netty-buffer-4.1.77.Final.jar' dependency of 'ballerina/http'
                'netty-handler-4.1.71.Final.jar' dependency of 'ballerinax/redis' conflict with 'netty-handler-4.1.77.Final.jar' dependency of 'ballerina/http'
                'netty-common-4.1.77.Final.jar' dependency of 'ballerina/http' conflict with 'netty-common-4.1.71.Final.jar' dependency of 'ballerinax/redis'
        target/bin/negotiator.jar
```

The reason is because the `http` module recently updated its netty version for latest due to security vulnerabilities and the relevant dependencies have been found to be in the previous version in `redis` . As a current work around we can update the `redis` version with latest netty version and use in Ballerina version 2201.0.4  .

### Related issues

I am trying to do [...] but [...]

**Comment by kapilraajP** [comment]
Redis connector version `2.2.2` is released to the DEV with the netty version update to `v4.1.77.Final`

**Comment by kapilraajP** [comment]
## RCA and QA Checklist

### RCA
1. Details

Update the Netty Maven dependency version of the connector from 4.1.71.Final to 4.1.77.Final
While using redis connector and http module together conflicts warnings arises. As ballerina http module recently updated its netty version for the latest due to security vulnerabilities. The relevant dependencies have been found to be in the previous version in Redis. As a current workaround netty version in Ballerina.toml is updated with the latest as in http module

#### Checklist

- [x] `StoryPoint/` label added:


- [x] `ValuePoint/` label added:


- [x] `Reason/` label added: 

- [x] `Resolution/` label added:

#### Original PR that introduced the bug:


### QA
2. Automation tests

 N/A

3. E2E smoke tests

 N/A

**Comment by kapilraajP** [comment]
Closing this issue since the Redis connector is released to all environments and verified the above issue
