### ISSUE TITLE
[Improvement]: Handling attachment size

### ISSUE THREAD

**Issue by abeykoon** [ballerina-platform/ballerina-extended-library#49]
### Connector Name

module/gmail (Gmail)

### Suggested improvement

Check attachment size, validate and throw an error before invoking API. Choreo UI should support this properly when connector is onboarded. 

### Related issues

As per Google [API reference](https://developers.google.com/gmail/api/v1/reference/users/messages/send), attachment size should not exceed 35MB. However, the module doesn't check the size of each attachment before making the API call. The existing approach where the error is handled by the client after receiving the response from the Google server is inefficient.

**Comment by abeykoon** [comment]
Note sure issue is valid now. Moved from https://github.com/ballerina-platform/module-ballerinax-googleapis.gmail/issues/55. @kasthuriraajan could you have a look?

**Comment by kasthuriraajan** [comment]
For the suggested solution, we need to upload the entire attachment and need to check the file size to throw a size exceed error. After having a discussion with @indikasampath2000  & @abeykoon  we decided to not to do this in this manner, since it's not a optimal solution. Instead of that we decided to inform the user via connector API documentation about the size limit. Any way when a user upload a large file which is exceeding the limit, the Gmail API endpoint will throw an error. We will return that to user.
