### ISSUE TITLE
[Task]: Integrate codecov with Ballerina extended library repos

### ISSUE THREAD

**Issue by NipunaRanasinghe** [ballerina-platform/ballerina-extended-library#533]
### Connector Name

other (None Listed Above)

### Task Description

Need to integrate codecov with Ballerina extended library repos to
1. View overall code coverage information on the Ballerinax dashboard (similar to the `Code Coverage` column in https://github.com/ballerina-platform/ballerina-standard-library#ballerina-modules)
2. View code coverage diff on each pull request

**Comment by heshanpadmasiri** [comment]
Among the pure ballerina connectors, some of them have unit tests failing (so we won't get code coverage reports for them)
## 1. Cases where the master/main branch is already failing unit tests
+ [module-ballerinax-microsoft.excel](https://github.com/ballerina-platform/module-ballerinax-microsoft.excel)
+ [module-ballerinax-microsoft.onedrive](https://github.com/ballerina-platform/module-ballerinax-microsoft.onedrive)
+ [module-ballerinax-microsoft.onenote](https://github.com/ballerina-platform/module-ballerinax-microsoft.onenote)
+ [module-ballerinax-microsoft.outlook.calendar](https://github.com/ballerina-platform/module-ballerinax-microsoft.outlook.calendar)
+ [module-ballerinax-microsoft.outlook.mail](https://github.com/ballerina-platform/module-ballerinax-microsoft.outlook.mail) (Has a PR to fix the tests)
+ [module-ballerinax-peoplehr](https://github.com/ballerina-platform/module-ballerinax-peoplehr)
## 2. Cases where unit tests previously were not executed as part of CI
+ [module-ballerinax-azure.ad](https://github.com/ballerina-platform/module-ballerinax-azure.ad)
+ [module-ballerinax-microsoft.teams](https://github.com/ballerina-platform/module-ballerinax-microsoft.teams)
+ [module-ballerinax-twilio](https://github.com/ballerina-platform/module-ballerinax-twilio)

@NipunaRanasinghe I have made PRs for these from forks, to avoid branches in the main repo triggering notifications due to build failures. I am assuming the reason for most of the above is due to stale/invalid security keys (some have pending PRs for fixing unit tests). We can merge the PRs now or fix the test cases first.

**Comment by NipunaRanasinghe** [comment]
@heshanpadmasiri Good work so far! 🙂 

Regarding the issues you mentioned,
- Currently all Microsoft connectors (category 1) are failing due to the expired tokens, and we are in the process of updating the tokens as we no longer can use the old Azure A/C for the API, it takes more time than we expected.

- In category 2, we have concerns on the twilio and cosmosdb connectors, as for both we  we use paid subscriptions and we pay based on the usage. Therefore we have added a separate build for the twilio connector to run tests once per month https://github.com/ballerina-platform/module-ballerinax-twilio/blob/master/.github/workflows/monthly-build-with-tests.yml
probably we can integrate codecov to the same build.

**Comment by heshanpadmasiri** [comment]
### Connectors without tests
+ [module-ballerinax-snowflake](https://github.com/ballerina-platform/module-ballerinax-snowflake)
+ [module-ballerinax-cdata.connect](https://github.com/ballerina-platform/module-ballerinax-cdata.connect)

**Comment by NipunaRanasinghe** [comment]
Closing as all the related PRs are merged.
